import { defineConfig } from 'orval'

export default defineConfig({
  'ess-api': {
    input: {
      target: './swagger.json',
    },
    output: {
      target: './src/services/generated/essApi.ts',
      client: 'axios',
      override: {
        mutator: {
          path: './src/utils/orval-mutator.ts',
          name: 'customInstance',
        },
        header: (info) => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [`${info.title}`] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
  },
})
